AWSTemplateFormatVersion: '2010-09-09'
Description: 'Eudaura Landing Page EC2 Infrastructure'

Parameters:
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 Key Pair for SSH access
    ConstraintDescription: Must be an existing EC2 KeyPair

  InstanceType:
    Type: String
    Default: t3.small
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
    Description: EC2 instance type

  YourIPAddress:
    Type: String
    Description: Your IP address for SSH access (e.g., 1.2.3.4/32)
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])/([0-9]|[1-2][0-9]|3[0-2])$'

Resources:
  # Security Group
  EudauraSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: eudaura-web-sg
      GroupDescription: Security group for Eudaura landing page
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref YourIPAddress
          Description: SSH from your IP
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: HTTP from anywhere
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: HTTPS from anywhere
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
      Tags:
        - Key: Name
          Value: eudaura-web-sg

  # Elastic IP
  EudauraEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: eudaura-web-eip

  # EC2 Instance
  EudauraEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0c02fb55956c7d316  # Amazon Linux 2023 in us-east-1
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref EudauraSecurityGroup
      IamInstanceProfile: !Ref EudauraInstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          exec > >(tee /var/log/user-data.log)
          exec 2>&1
          
          echo "Starting Eudaura setup at $(date)"
          
          # Update system
          yum update -y
          
          # Install Node.js 20
          curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
          yum install -y nodejs git
          
          # Install PM2 globally
          npm install -g pm2
          
          # Install Nginx
          amazon-linux-extras install nginx1 -y
          
          # Download and run setup
          cd /home/ec2-user
          curl -sSL https://raw.githubusercontent.com/cerberus100/eudaralander/main/eudaura-site/deploy/setup-ec2.sh -o setup-ec2.sh
          chmod +x setup-ec2.sh
          
          # Create marker for CloudFormation
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EudauraEC2 --region ${AWS::Region}
          
      Tags:
        - Key: Name
          Value: eudaura-web-server
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT15M

  # EIP Association
  EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref EudauraEC2
      EIP: !Ref EudauraEIP

  # IAM Role for EC2
  EudauraEC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: eudaura-ec2-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Policies:
        - PolicyName: EudauraS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource: arn:aws:s3:::eudaura-documents/*
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource: arn:aws:s3:::eudaura-documents

  # Instance Profile
  EudauraInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EudauraEC2Role

  # CloudWatch Alarms
  CPUAlarmHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alarm if CPU too high
      AlarmName: eudaura-cpu-high
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: InstanceId
          Value: !Ref EudauraEC2

  StatusCheckFailed:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alarm if instance fails status check
      AlarmName: eudaura-status-check
      MetricName: StatusCheckFailed
      Namespace: AWS/EC2
      Statistic: Maximum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: InstanceId
          Value: !Ref EudauraEC2

Outputs:
  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !Ref EudauraEIP
    Export:
      Name: !Sub ${AWS::StackName}-PublicIP

  SSHCommand:
    Description: SSH command to connect to the instance
    Value: !Sub 'ssh -i ${KeyPairName}.pem ec2-user@${EudauraEIP}'

  WebURL:
    Description: URL of the website (after DNS update)
    Value: !Sub 'http://${EudauraEIP}'

  InstanceId:
    Description: Instance ID
    Value: !Ref EudauraEC2
    Export:
      Name: !Sub ${AWS::StackName}-InstanceId
